# Generated by Django 3.0.5 on 2020-10-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='routerapi',
            fields=[
                ('sapid', models.CharField(max_length=18)),
                ('hostname', models.CharField(max_length=14)),
                ('loopback', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('macip', models.CharField(max_length=17)),
                ('is_delete', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
